//
// Created by Remi Peyras on 13/11/2021.
//

#ifndef COMPUTERGRAPHIC_ASSIGNMENT_03_EXERCISEFOURTH_HPP
#define COMPUTERGRAPHIC_ASSIGNMENT_03_EXERCISEFOURTH_HPP


class ExerciseFourth {

};


#endif //COMPUTERGRAPHIC_ASSIGNMENT_03_EXERCISEFOURTH_HPP
